

  CREATE TABLE "LW10"."SESWSSOR_CONFERENCE_MEETS" 
   (	"ID" NUMBER(19,0), 
	"VERSION" NUMBER(*,0) DEFAULT 0, 
	"DELETE_TIME" TIMESTAMP (6), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"CREATE_TIME" TIMESTAMP (6), 
	"DELETE_STAFF_ID" NUMBER(19,0), 
	"MODIFY_STAFF_ID" NUMBER(19,0), 
	"CREATE_STAFF_ID" NUMBER(19,0), 
	"VALID" NUMBER(*,0) DEFAULT 1, 
	"CID" NUMBER(19,0), 
	"SORT" NUMBER(*,0), 
	"EFFECTIVE_STATE" NUMBER(19,0), 
	"PROCESS_VERSION" NUMBER(*,0), 
	"PROCESS_KEY" VARCHAR2(510 CHAR), 
	"DEPLOYMENT_ID" NUMBER(19,0), 
	"GROUP_ID" NUMBER(19,0), 
	"STATUS" NUMBER(19,0), 
	"EFFECT_TIME" TIMESTAMP (6), 
	"EFFECT_STAFF_ID" NUMBER(19,0), 
	"OWNER_DEPARTMENT_ID" NUMBER(19,0), 
	"OWNER_POSITION_ID" NUMBER(19,0), 
	"OWNER_STAFF_ID" NUMBER(19,0), 
	"POSITION_LAY_REC" VARCHAR2(510 CHAR), 
	"CREATE_POSITION_ID" NUMBER(19,0), 
	"CREATE_DEPARTMENT_ID" NUMBER(19,0), 
	"CONFERENCE_NAME" VARCHAR2(510 CHAR), 
	"CONFERENCE_DATE" TIMESTAMP (6), 
	"CONFERENCE_PARTICIPANTS" NUMBER(19,0), 
	"CONFERENCE_VENUE" VARCHAR2(510 CHAR), 
	"CONFERENCE_THEME" VARCHAR2(510 CHAR), 
	"CONVENE_DEPARTMENT" NUMBER(19,0), 
	"ACTUAL_PARTCIPANTS" NUMBER(19,0), 
	"CONFERENCE_ELEMENT" VARCHAR2(510 CHAR), 
	"CONFERENCE_REMARK" VARCHAR2(510 CHAR), 
	"TABLE_INFO_ID" NUMBER(19,0), 
	"TABLE_NO" VARCHAR2(510 CHAR), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIWEI"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIWEI" ;
 

   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."VERSION" IS '版本信息';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."DELETE_TIME" IS '删除时间';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."MODIFY_TIME" IS '修改时间';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."CREATE_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."DELETE_STAFF_ID" IS '删除者';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."MODIFY_STAFF_ID" IS '修改者';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."CREATE_STAFF_ID" IS '创建者';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."VALID" IS '是否有效';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."CID" IS '公司ID';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."SORT" IS '顺序';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."EFFECTIVE_STATE" IS '生效状态';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."PROCESS_VERSION" IS '流程版本';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."PROCESS_KEY" IS '流程key';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."DEPLOYMENT_ID" IS '流程ID';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."GROUP_ID" IS '组ID';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."STATUS" IS '状态';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."EFFECT_TIME" IS '生效时间';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."EFFECT_STAFF_ID" IS '生效人';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."OWNER_DEPARTMENT_ID" IS '所有者部门';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."OWNER_POSITION_ID" IS '所有者主岗';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."OWNER_STAFF_ID" IS '所有者';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."POSITION_LAY_REC" IS '岗位层级结构';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."CREATE_POSITION_ID" IS '创建岗位';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."CREATE_DEPARTMENT_ID" IS '创建部门';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."CONFERENCE_NAME" IS '会议名称';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."CONFERENCE_DATE" IS '会议时间';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."CONFERENCE_PARTICIPANTS" IS '参与人员';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."CONFERENCE_VENUE" IS '会议地点';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."CONFERENCE_THEME" IS '会议主题';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."CONVENE_DEPARTMENT" IS '召集部门';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."ACTUAL_PARTCIPANTS" IS '实际参与人员';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."CONFERENCE_ELEMENT" IS '主要内容';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."CONFERENCE_REMARK" IS '备注';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."TABLE_INFO_ID" IS '表单id';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_CONFERENCE_MEETS"."TABLE_NO" IS '单据编号';
 
   COMMENT ON TABLE "LW10"."SESWSSOR_CONFERENCE_MEETS"  IS '安委会会议';
 