

  CREATE TABLE "LW10"."SESWSSOR_SECURITY_CMMTTEES" 
   (	"ID" NUMBER(19,0), 
	"VERSION" NUMBER(*,0) DEFAULT 0, 
	"DELETE_TIME" TIMESTAMP (6), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"CREATE_TIME" TIMESTAMP (6), 
	"DELETE_STAFF_ID" NUMBER(19,0), 
	"MODIFY_STAFF_ID" NUMBER(19,0), 
	"CREATE_STAFF_ID" NUMBER(19,0), 
	"VALID" NUMBER(*,0) DEFAULT 1, 
	"CID" NUMBER(19,0), 
	"SORT" NUMBER(*,0), 
	"EFFECTIVE_STATE" NUMBER(19,0), 
	"PROCESS_VERSION" NUMBER(*,0), 
	"PROCESS_KEY" VARCHAR2(510 CHAR), 
	"DEPLOYMENT_ID" NUMBER(19,0), 
	"GROUP_ID" NUMBER(19,0), 
	"STATUS" NUMBER(19,0), 
	"EFFECT_TIME" TIMESTAMP (6), 
	"EFFECT_STAFF_ID" NUMBER(19,0), 
	"OWNER_DEPARTMENT_ID" NUMBER(19,0), 
	"OWNER_POSITION_ID" NUMBER(19,0), 
	"OWNER_STAFF_ID" NUMBER(19,0), 
	"POSITION_LAY_REC" VARCHAR2(510 CHAR), 
	"CREATE_POSITION_ID" NUMBER(19,0), 
	"CREATE_DEPARTMENT_ID" NUMBER(19,0), 
	"CMMTTEE_NAME" VARCHAR2(510 CHAR), 
	"CMMTTEE_LEVEL" VARCHAR2(510 CHAR), 
	"TELEPHONE" VARCHAR2(510 CHAR), 
	"CMMTTEE_BRIEF" VARCHAR2(510 CHAR),
	"TABLE_INFO_ID" NUMBER(19,0), 
	"TABLE_NO" VARCHAR2(510 CHAR), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIWEI"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIWEI" ;
 

   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."VERSION" IS '版本信息';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."DELETE_TIME" IS '删除时间';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."MODIFY_TIME" IS '修改时间';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."CREATE_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."DELETE_STAFF_ID" IS '删除者';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."MODIFY_STAFF_ID" IS '修改者';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."CREATE_STAFF_ID" IS '创建者';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."VALID" IS '是否有效';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."CID" IS '公司ID';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."SORT" IS '顺序';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."EFFECTIVE_STATE" IS '生效状态';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."PROCESS_VERSION" IS '流程版本';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."PROCESS_KEY" IS '流程key';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."DEPLOYMENT_ID" IS '流程ID';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."GROUP_ID" IS '组ID';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."STATUS" IS '状态';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."EFFECT_TIME" IS '生效时间';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."EFFECT_STAFF_ID" IS '生效人';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."OWNER_DEPARTMENT_ID" IS '所有者部门';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."OWNER_POSITION_ID" IS '所有者主岗';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."OWNER_STAFF_ID" IS '所有者';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."POSITION_LAY_REC" IS '岗位层级结构';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."CREATE_POSITION_ID" IS '创建岗位';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."CREATE_DEPARTMENT_ID" IS '创建部门';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."CMMTTEE_NAME" IS '安委会名称';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."CMMTTEE_LEVEL" IS '安委会等级';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."TELEPHONE" IS '联系方式';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."CMMTTEE_BRIEF" IS '安委会简介';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."TABLE_INFO_ID" IS '表单id';
 
   COMMENT ON COLUMN "LW10"."SESWSSOR_SECURITY_CMMTTEES"."TABLE_NO" IS '单据编号';
 
   COMMENT ON TABLE "LW10"."SESWSSOR_SECURITY_CMMTTEES"  IS '安委会信息';
 