DELETE AM_RECORDS  WHERE ALARMID in (SELECT ID FROM AM_OBJECTS WHERE REGIONID IS NULL);
DELETE AM_POLICYS WHERE ALARMID in (SELECT ID FROM AM_OBJECTS WHERE REGIONID IS NULL);
DELETE AM_VARS WHERE ALARMID in (SELECT ID FROM AM_OBJECTS WHERE REGIONID IS NULL);
DELETE AM_NOTIFY WHERE ALARMID in (SELECT ID FROM AM_OBJECTS WHERE REGIONID IS NULL);
DELETE AM_OBJECTAUTH WHERE ALARMID in (SELECT ID FROM AM_OBJECTS WHERE REGIONID IS NULL);
DELETE AM_JOBOBJECTAUTH WHERE ALARMID in (SELECT ID FROM AM_OBJECTS WHERE REGIONID IS NULL);
DELETE AM_OBJECTS WHERE id in (SELECT ID FROM AM_OBJECTS WHERE REGIONID IS NULL);